### ISSUE TITLE
Works perfectly in Wayland

### ISSUE THREAD

**Issue by edent** [hermes83/compiz-alike-windows-effect#3]
Not an issue - this is praise! Trying this on Pop OS using Wayland. Wobbly Windows FTW!

Makes my laptop fans roar though.

**Comment by hermes83** [comment]
Thanks @edent
I tried to optimize the code with the last commit but, unfortunately, there is not much that an extension's code can do in order to improve the mutter / clutter performance.
The latest change has not yet been released on extensions.gnome.org for asessment, but I think didn't changes much compared to previous commit in terms of performances.

**Comment by hermes83** [comment]
Added some performance improvements with the last commit
